"""
Long winded constants and such live here. Most notably the LANGS tuple.
Unlike in the php version no sql is necessary to add a new language. You only
need to append a new tuple and restart the server. This is equally true
for other constants that appear here.
"""


LANGS = (
    ("afr", "Afrikaans"),
    ("ain", "Ainu"),
    ("sqi", "Albanian"),
    ("arq", "Algerian Arabic"),
    ("grc", "Ancient Greek"),
    ("ara", "Arabic"),
    ("hye", "Armenian"),
    ("ast", "Asturian"),
    ("aze", "Azerbaijani"),
    ("eus", "Basque"),
    ("bel", "Belarusian"),
    ("ben", "Bengali"),
    ("ber", "Berber"),
    ("bos", "Bosnian"),
    ("bre", "Breton"),
    ("bul", "Bulgarian"),
    ("yue", "Cantonese"),
    ("cat", "Catalan"),
    ("cha", "Chamorro"),
    ("cmn", "Chinese"),
    ("ckt", "Chukchi"),
    ("cor", "Cornish"),
    ("hrv", "Croatian"),
    ("cycl", "CycL"),
    ("ces", "Czech"),
    ("dan", "Danish"),
    ("nld", "Dutch"),
    ("arz", "Egyptian Arabic"),
    ("eng", "English"),
    ("epo", "Esperanto"),
    ("est", "Estonian"),
    ("ewe", "Ewe"),
    ("fao", "Faroese"),
    ("fin", "Finnish"),
    ("fra", "French"),
    ("fry", "Frisian"),
    ("glg", "Galician"),
    ("kat", "Georgian"),
    ("deu", "German"),
    ("grn", "Guarani"),
    ("heb", "Hebrew"),
    ("hil", "Hiligaynon"),
    ("hin", "Hindi"),
    ("hun", "Hungarian"),
    ("isl", "Icelandic"),
    ("ido", "Ido"),
    ("ind", "Indonesian"),
    ("ina", "Interlingua"),
    ("ile", "Interlingue"),
    ("acm", "Iraqi Arabic"),
    ("gle", "Irish"),
    ("ita", "Italian"),
    ("jpn", "Japanese"),
    ("xal", "Kalmyk"),
    ("kaz", "Kazakh"),
    ("khm", "Khmer"),
    ("tlh", "Klingon"),
    ("kor", "Korean"),
    ("avk", "Kotava"),
    ("kur", "Kurdish"),
    ("ksh", "Kolsch"),
    ("lld", "Ladin"),
    ("lad", "Ladino"),
    ("lao", "Lao"),
    ("lat", "Latin"),
    ("lvs", "Latvian"),
    ("lzh", "Literary Chinese"),
    ("lit", "Lithuanian"),
    ("jbo", "Lojban"),
    ("dsb", "Lower Sorbian"),
    ("nds", "Low Saxon"),
    ("mlg", "Malagasy"),
    ("zsm", "Malay"),
    ("mal", "Malayalam"),
    ("mlt", "Maltese"),
    ("mri", "Maori"),
    ("mar", "Marathi"),
    ("ell", "Modern Greek"),
    ("mon", "Mongolian"),
    ("npi", "Nepali"),
    ("nob", "Norwegian (Bokmal)"),
    ("non", "Norwegian (Nynorsk)"),
    ("nov", "Novial"),
    ("oci", "Occitan"),
    ("orv", "Old East Slavic"),
    ("ang", "Old English"),
    ("prg", "Old Prussian"),
    ("tpw", "Old Tupi"),
    ("oss", "Ossetian"),
    ("pes", "Persian"),
    ("pcd", "Picard"),
    ("pms", "Piemontese"),
    ("pol", "Polish"),
    ("por", "Portuguese"),
    ("pnb", "Punjabi"),
    ("que", "Quechua"),
    ("qya", "Quenya"),
    ("ron", "Romanian"),
    ("roh", "Romansh"),
    ("rus", "Russian"),
    ("san", "Sanskrit"),
    ("gla", "Scottish Gaelic"),
    ("srp", "Serbian"),
    ("wuu", "Shanghainese"),
    ("scn", "Sicilian"),
    ("sjn", "Sindarin"),
    ("slk", "Slovak"),
    ("slv", "Slovenian"),
    ("spa", "Spanish"),
    ("bod", "Standard Tibetan"),
    ("swh", "Swahili"),
    ("swe", "Swedish"),
    ("tgl", "Tagalog"),
    ("tgk", "Tajik"),
    ("tat", "Tatar"),
    ("tel", "Telugu"),
    ("nan", "Teochew"),
    ("tha", "Thai"),
    ("toki", "Toki Pona"),
    ("tpi", "Tok Pisin"),
    ("tur", "Turkish"),
    ("ukr", "Ukrainian"),
    ("hsb", "Upper Sorbian"),
    ("urd", "Urdu"),
    ("uig", "Uyghur"),
    ("uzb", "Uzbek"),
    ("vie", "Vietnamese"),
    ("vol", "Volapuk"),
    ("cym", "Welsh"),
    ("xho", "Xhosa"),
    ("yid", "Yiddish"),
)

# use Log.get_type_display() to get the readable part
# for display in templates
LOG_ACTIONS = (
    ('sad', 'Sentence added'),
    ('sed', 'Sentence edited'),
    ('srd', 'Sentence removed'),
    ('sld', 'Sentence locked'),
    ('sul', 'Sentence unlocked'),
    ('soa', 'Sentence adopted'),
    ('sor', 'Sentence released'),
    ('slc', 'Sentence language changed'),
    ('lad', 'Link added'),
    ('lrd', 'Link removed'),
    ('cma', 'Comment added'),
    ('cme', 'Comment edited'),
    ('cmr', 'Comment removed'),
    ('tad', 'Tag added'),
    ('trd', 'Tag removed'),
    ('usd', 'User subscribed'),
    ('uud', 'User unsubscribed'),
    ('cad', 'Correction added'),
    ('ced', 'Correction edited'),
    ('crd', 'Correction removed'),
    ('crj', 'Correction rejected'),
    ('cac', 'Correction accepted'),
    ('cfd', 'Correction forced'),
)
